[build]
  command = "pnpm --filter svelte-seo-meta-tags build && pnpm --filter plain build"
  publish = "packages/plain/build"

#[[plugins]]
#  package = "/.netlify/netlify-plugin-pnpm"

# [[plugins]]
#   package = "netlify-plugin-inline-critical-css"
#     [plugins.inputs]
#       fileFilter = ['index.html']
#       directoryFilter = ['!*']

#[[plugins]]
#  package = "netlify-plugin-a11y"
#    [plugins.inputs]
#      checkPaths = ['/']
#      # resultMode = "warn"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "packages/site/build"
    trailingSlash = true
