[build]
  command = "npm run build"
  publish = "packages/client/dist"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
    [plugins.inputs]
      fileFilter = ['index.html']
      directoryFilter = ['!*']

[[plugins]]
  package = "netlify-plugin-a11y"
    [plugins.inputs]
      checkPaths = ['/']
      # resultMode = "warn"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "packages/client/dist"
    trailingSlash = true
    exclude = [
      "./dist/404.html"
    ]