name = "blog-comment-worker"
workers_dev = true
compatibility_date = "2022-07-12"
account_id = "a98e9f2d8c8488b65f5c8c91ad82ec53"

main = "./dist/index.js"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'teemukoivisto-xyz'

[vars]
GITHUB_OAUTH_CLIENT_ID = "Iv1.86945abab807256c"
GOOGLE_OAUTH_CLIENT_ID = "96348240705-m5l5kj7ja65fgtgo72sqgnuasj737f3n.apps.googleusercontent.com"
