name = "teemukoivisto-xyz-worker"
workers_dev = true
compatibility_date = "2022-07-12"
account_id = "a98e9f2d8c8488b65f5c8c91ad82ec53"

main = "./dist/index.js"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'teemukoivisto-xyz'

[[kv_namespaces]]
binding = "AUTHORIZED_USERS"
id = "ae434da713794ba7b0ffde18bcab49b8"

[vars]
SUPER_USER_ID = "10279942"
GITHUB_OAUTH_CLIENT_ID = "Iv1.5a4d92744e8c2767"
GOOGLE_OAUTH_CLIENT_ID = "96348240705-m5l5kj7ja65fgtgo72sqgnuasj737f3n.apps.googleusercontent.com"
